substitutions:
  device_name: esp-rfid
  friendly_name: ESP RFID

esphome:
  includes:
    - wiegand_device.h
  name: ${device_name}
  platform: ESP8266
  board: esp12e
  esp8266_restore_from_flash: true

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: ""

wifi:
  ssid: ""
  password: ""

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${friendly_name} Fallback Hotspot"
    password: "1ME5qx4VcOd4"
  domain: ".example.com"

captive_portal:

sensor:
# Reports the WiFi signal strength
- platform: wifi_signal
  name: ${friendly_name} Signal
  update_interval: 60s

# Reports how long the device has been powered (in minutes)
- platform: uptime
  name: ${friendly_name} Uptime
  filters:
    - lambda: return x / 60.0;
  unit_of_measurement: minutes

text_sensor:
- platform: custom
  lambda: |-
    auto wiegand = new WiegandReader(D6, D7);
    App.register_component(wiegand);
    return {wiegand};
  text_sensors:
    name: "${friendly_name} Card ID"
    on_value:
      then:
        - homeassistant.tag_scanned: !lambda |-
            return x;

binary_sensor:
  - platform: status
    name: "${friendly_name} Status"
  - platform: gpio
    pin:
      number: GPIO4
      mode: INPUT_PULLUP
      inverted: True
    name: "${friendly_name} Button"
    device_class: door
    filters:
      - delayed_on: 10ms
    on_press:
    - switch.turn_on: relay
  - platform: gpio
    pin:
      number: GPIO14
      mode: INPUT_PULLUP
      inverted: True
    name: "${friendly_name} Doorbell"
    device_class: occupancy
    filters:
      - delayed_on: 10ms

switch:
  - platform: gpio
    pin: GPIO5
    id: relay
    name: "${friendly_name} Remote"
    icon: "mdi:gate"
    on_turn_on:
    - delay: 1000ms
    - switch.turn_off: relay

status_led:
  pin: GPIO2