substitutions:
  device_name: esp-rfid
  friendly_name: ESP RFID

esphome:
  includes:
    - wiegand_device.h
  name: ${device_name}
  platform: ESP8266
  board: esp12e
  esp8266_restore_from_flash: true

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: ""

wifi:
  ssid: ""
  password: ""

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${friendly_name} Fallback Hotspot"
    password: "1ME5qx4VcOd4"
  domain: ".example.com"

captive_portal:

text_sensor:
- platform: custom
  lambda: |-
    auto wiegand = new WiegandReader(D6, D7);
    App.register_component(wiegand);
    return {wiegand};
  text_sensors:
    name: "Card ID"
    on_value:
      then:
        - homeassistant.tag_scanned: !lambda |-
            return x;

switch:
  - platform: gpio
    pin: GPIO4
    id: button
    name: "Gate Controller Button"
    on_turn_on:
    - switch.turn_on: relay
    - delay: 500ms
    - switch.turn_off: relay
  - platform: gpio
    pin: GPIO5
    id: relay
    name: "Gate Remote"
    icon: "mdi:gate"
    on_turn_on:
    - delay: 1000ms
    - switch.turn_off: relay

status_led:
  pin: GPIO2

web_server:
  port: 80
