esphome:
  includes:
    - wiegand_device.h
  name: front-door-reader
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: "xxx"
  password: "xxx"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Door-Reader Fallback Hotspot"
    password: "xxx"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

text_sensor:
- platform: custom
  lambda: |-
    auto wiegand = new WiegandReader(D6, D7);
    App.register_component(wiegand);
    return {wiegand};

  text_sensors:
    name: "Card ID"
    on_value:
      then:
        - homeassistant.tag_scanned: !lambda |-
            return x;      
            
